= Secret Store - Examples - Client behind a proxy

This module builds a WAR file with the "backend" as a library. There's no explicit integration with the Secret Store,
so, all it needs is the Keycloak configuration.

To test the proxy approach, you need to start the proxy and the Wildfly server assembled under the `server` directory.
Refer to the instructions on the `proxy` module about how to start the proxy.

For a quick test, the services can be started this way, each command in a different terminal:
[source,bash]
----
$ java -jar ./proxy/target/secret-store-proxy-jar-with-dependencies.jar
$ examples/server/target/secret-store-examples-server-1.0.5.Final-SNAPSHOT/bin/standalone.sh
----

Once both services are started, these are the expected responses:

Non-authenticated response
[source,bash]
----
$ curl -v http://localhost:8080/behind-proxy/echo?message=aaa ; echo
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /behind-proxy/echo?message=aaa HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 302 Found
< Expires: 0
< Cache-Control: no-cache, no-store, must-revalidate
< X-Powered-By: Undertow/1
< Set-Cookie: OAuth_Token_Request_State=0/dac938df-f0ee-4029-a517-99b91fd00cd0
< Server: WildFly/10
< Pragma: no-cache
< Location: http://localhost:8080/auth/realms/secret-store/protocol/openid-connect/auth?response_type=code&client_id=secret-store&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fbehind-proxy%2Fecho?message%3Daaa&state=0%2Fdac938df-f0ee-4029-a517-99b91fd00cd0&login=true
< Date: Wed, 20 Jan 2016 11:44:21 GMT
< Connection: keep-alive
< Content-Length: 0
<
* Connection #0 to host localhost left intact
----

Authenticated response, sending the actual user credentials
[source,bash]
----
$ curl -v -u jdoe:password http://localhost:8080/behind-proxy/echo?message=aaa ; echo
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
* Server auth using Basic with user 'jdoe'
> GET /behind-proxy/echo?message=aaa HTTP/1.1
> Host: localhost:8080
> Authorization: Basic amRvZTpwYXNzd29yZA==
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Expires: 0
< Cache-Control: no-cache, no-store, must-revalidate
< X-Powered-By: Undertow/1
< Server: WildFly/10
< Pragma: no-cache
< Date: Wed, 20 Jan 2016 11:43:37 GMT
< Connection: keep-alive
< Content-Type: application/json
< Content-Length: 63
<
* Connection #0 to host localhost left intact
{"user":"28026b36-8fe4-4332-84c8-524e173a68bf","message":"aaa"}
----

Create a token
[source,bash]
----
$ curl -v -u jdoe:password -X POST -H 'Accept: application/json' http://localhost:8080/secret-store/v1/tokens/create ; echo
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
* Server auth using Basic with user 'jdoe'
> POST /secret-store/v1/tokens/create HTTP/1.1
> Host: localhost:8080
> Authorization: Basic amRvZTpwYXNzd29yZA==
> User-Agent: curl/7.43.0
> Accept: application/json
>
< HTTP/1.1 200 OK
< Expires: 0
< Cache-Control: no-cache, no-store, must-revalidate
< X-Powered-By: Undertow/1
< Server: WildFly/10
< Pragma: no-cache
< Date: Wed, 20 Jan 2016 11:41:56 GMT
< Connection: keep-alive
< Content-Type: application/json
< Content-Length: 90
<
* Connection #0 to host localhost left intact
{"key":"8bafee0b-ba71-4498-b4b7-a59d6240d42b","secret":"332fa1d9ba0987616132296d1b00d7c9"}
----

Sending the tokens directly to the backend
[source,bash]
----
$ curl -v -u 8bafee0b-ba71-4498-b4b7-a59d6240d42b:332fa1d9ba0987616132296d1b00d7c9 http://localhost:8080/behind-proxy/echo?message=aaa ; echo
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
* Server auth using Basic with user '8bafee0b-ba71-4498-b4b7-a59d6240d42b'
> GET /behind-proxy/echo?message=aaa HTTP/1.1
> Host: localhost:8080
> Authorization: Basic OGJhZmVlMGItYmE3MS00NDk4LWI0YjctYTU5ZDYyNDBkNDJiOjMzMmZhMWQ5YmEwOTg3NjE2MTMyMjk2ZDFiMDBkN2M5
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 401 Unauthorized
< Expires: 0
< Cache-Control: no-cache, no-store, must-revalidate
< X-Powered-By: Undertow/1
< Server: WildFly/10
< Pragma: no-cache
< Date: Wed, 20 Jan 2016 11:45:26 GMT
< Connection: keep-alive
< WWW-Authenticate: Bearer realm="secret-store", error="no_token", error_description="Bad status: 401"
< Content-Type: text/html;charset=UTF-8
< Content-Length: 71
<
* Connection #0 to host localhost left intact
<html><head><title>Error</title></head><body>Unauthorized</body></html>
----

Authenticated response, sending the newly created token, via the proxy running on port 8081
[source,bash]
----
$ curl -v -u 8bafee0b-ba71-4498-b4b7-a59d6240d42b:332fa1d9ba0987616132296d1b00d7c9 -x http://localhost:8081 http://localhost:8080/behind-proxy/echo?message=aaa ; echo
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8081 (#0)
* Server auth using Basic with user '8bafee0b-ba71-4498-b4b7-a59d6240d42b'
> GET http://localhost:8080/behind-proxy/echo?message=aaa HTTP/1.1
> Host: localhost:8080
> Authorization: Basic OGJhZmVlMGItYmE3MS00NDk4LWI0YjctYTU5ZDYyNDBkNDJiOjMzMmZhMWQ5YmEwOTg3NjE2MTMyMjk2ZDFiMDBkN2M5
> User-Agent: curl/7.43.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 OK
< Expires: 0
< Cache-Control: no-cache, no-store, must-revalidate
< X-Powered-By: Undertow/1
< Server: WildFly/10
< Pragma: no-cache
< Date: Wed, 20 Jan 2016 11:46:50 GMT
< Connection: keep-alive
< Content-Type: application/json
< Content-Length: 63
<
* Connection #0 to host localhost left intact
{"user":"28026b36-8fe4-4332-84c8-524e173a68bf","message":"aaa"}
----

Sending the username and password via the proxy (the proxy ignores and just relays the call to the backend)
[source,bash]
----
$ curl -v -u jdoe:password -x http://localhost:8081 http://localhost:8080/behind-proxy/echo?message=aaa ; echo
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8081 (#0)
* Server auth using Basic with user 'jdoe'
> GET http://localhost:8080/behind-proxy/echo?message=aaa HTTP/1.1
> Host: localhost:8080
> Authorization: Basic amRvZTpwYXNzd29yZA==
> User-Agent: curl/7.43.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 OK
< Expires: 0
< Cache-Control: no-cache, no-store, must-revalidate
< X-Powered-By: Undertow/1
< Server: WildFly/10
< Pragma: no-cache
< Date: Wed, 20 Jan 2016 11:47:51 GMT
< Connection: keep-alive
< Content-Type: application/json
< Content-Length: 63
<
* Connection #0 to host localhost left intact
{"user":"28026b36-8fe4-4332-84c8-524e173a68bf","message":"aaa"}
----

== License

Secret Store is released under Apache License, Version 2.0 as described in the link:LICENSE[LICENSE] document

----
   Copyright 2015 Red Hat, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
----
